CREATE DATABASE db_laboratorios;

USE db_laboratorios;

-- USERS TABLE
CREATE TABLE users(
    id INT(11) NOT NULL AUTO_INCREMENT,
    email VARCHAR(30) NOT NULL, -- a218201284@unison.mx (20)
    alt_email VARCHAR(40) NOT NULL, -- EMAIL ALTERNATIVO
    password VARCHAR(60) NOT NULL,
    fullname VARCHAR(255) NOT NULL,
    birthday DATE NOT NULL, -- YYYY-MM-DD 
    gender VARCHAR(1),   -- PUEDE SER NULO
    cellphone VARCHAR(15) NOT NULL,  -- 6622781757 (10)
    diseases VARCHAR(255),  -- ALGUNA ENFERMEDAD

    PRIMARY KEY (id)    -- ID LLAVE PRIMARIA
);

-- ALTER TABLE users
--     ADD PRIMARY KEY (id);

-- ALTER TABLE users
--     MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 2;

DESCRIBE users;     -- PARA VERIFICAR QUE SE HAYA CREADO CORRECTAMENTE

-- LINKS TABLE
CREATE TABLE requests (
    id INT(11) NOT NULL AUTO_INCREMENT,
    user_id INT(11),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- FUNCION QUE TOMA LA FECHA ACTUAL
    request_date DATETIME NOT NULL,
    lab_code VARCHAR(10) NOT NULL,
    comments TEXT,

    -- PARA TENER UNA REFERENCIA A UN USUARIO
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id), -- LLAVE FORANEA
    PRIMARY KEY(id)
);

-- ALTER TABLE links
--     ADD PRIMARY KEY (id);

-- ALTER TABLE links
--     MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 2;

DESCRIBE requests;